authentication:
  allowed_users:
  - username: admin
    password: admin
  - username: root
    password: root
  - username: user
    password: user
banner: 220 ProFTPD 1.3.5e Server [ftp.example.com] FTP server ready
ftp:
  max_connections: 10
  connection_limit: 32768
