authentication:
  allowed_users:
    - username: "admin"
      password: "admin123"
    - username: "user"
      password: "password123"

ftp:
  banner: "220 ProFTPD 1.3.5e Server [ftp.example.com] FTP server ready"
  max_connections: 10
  connection_limit: 32768