authentication:
  allowed_users:
  - username: admin
    password: admin123
  - username: root
    password: toor
  - username: user
    password: password
banner: 220 ProFTPD 1.3.5e Server [ftp.example.com] FTP server ready
ftp:
  max_connections: 10
  connection_limit: 32768
