authentication:
  allowed_users:
  - username: admin
    password: admin
  - username: root
    password: root
  - username: user
    password: user
banner: SSH Hoenypot
ssh_key_path: ssh_host_rsa_key
